version: '3.7'

# STIG Manager docker-compose orchestration
# Maintainer: carl.a.smigielski@saic.com

services:
  auth:
    image: ${STIGMAN_DOCKER_REPO}/auth:${STIGMAN_DOCKER_TAG}
    build: ./keycloak
    ports:
      - "8080:8080"
      - "8443:8443"
  db:
    image: mysql:8.0
    ports:
      - "50011:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
  api:
    image: ${STIGMAN_DOCKER_REPO}/api:${STIGMAN_DOCKER_TAG}
    build: ../
    environment:
      - STIGMAN_API_PORT
      - STIGMAN_DB_TYPE
      - STIGMAN_DB_HOST
      - STIGMAN_DB_PORT
      - STIGMAN_DB_USER
      - STIGMAN_DB_PASSWORD
      - STIGMAN_DB_SCHEMA
      - STIGMAN_SUPERUSER
      - STIGMAN_SWAGGER_ENABLED
      - STIGMAN_SWAGGER_SERVER
      - STIGMAN_SWAGGER_REDIRECT
      - STIGMAN_API_AUTHORITY
      - STIGMAN_CLIENT_ENABLED
      - STIGMAN_CLIENT_API_BASE
      - STIGMAN_CLIENT_KEYCLOAK_REALM
      - STIGMAN_CLIENT_KEYCLOAK_AUTH
      - STIGMAN_CLIENT_KEYCLOAK_CLIENTID
    init: true
    ports:
      - "54000:54000"
