name: Publish Docker image
on:
  push:
    branches:
      - phase-1-dev
    tags:
      - workflowTest
  workflow_dispatch:
  


jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_ORG_OWNER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ORG_OWNER_PW }}
      - 
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
#           pull: true
          push: true
#           build-args:
#           cache-from: type=registry,ref=myorg/myrepository:latest
#           cache-to: type=inline
          tags: nuwcdivnpt/stig-manager-test:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      -
        name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_ORG_OWNER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ORG_OWNER_PW }}
          repository: nuwcdivnpt/stig-manager-test
          short-description: An API and Web client for managing STIG assessments.
          readme-filepath: ./docs/DockerHub_Readme.md
          
          
          

          
          
          
          
          
